CREATE TABLE [rrec].[contratos] (
    [id_contrato]                     INT             NOT NULL,
    [clave_estudiante]                INT             NOT NULL,
    [Periodo (CON)]                   VARCHAR (6)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Descripción periodo (CON)]       NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [No. de contrato]                 VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [orden_programa_contrato]         BIGINT          NULL,
    [Clave del programa]              NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa]           INT             NULL,
    [Programa]                        NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_programa_contrato_alterno] INT             NULL,
    [Clave del programa alterno]      NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa_alterno]   INT             NULL,
    [Programa alterno]                NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave de la vía de admisión]     NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_via_admision]              INT             NULL,
    [Vía de admisión]                 NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del status del contrato]   NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_contrato_estado]           INT             NULL,
    [Status del contrato]             NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [rut]                             VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [id_fecha_contrato]               INT             NOT NULL,
    [Fecha del contrato]              DATETIME        NULL,
    [tp_retracto]                     INT             NOT NULL,
    [tipo_retracto]                   VARCHAR (21)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [fg_retracto]                     INT             NOT NULL,
    [Es_retracto]                     VARCHAR (14)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [no_retracto]                     NUMERIC (10)    NOT NULL,
    [fe_fecha_retracto]               DATETIME2 (7)   NULL,
    [no_monto]                        NUMERIC (16, 2) NOT NULL,
    [no_monto_pagado]                 NUMERIC (16, 2) NOT NULL,
    [nb_codigo]                       NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [no_orden_facultad]               INT             NULL,
    [nb_facultad]                     NVARCHAR (64)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Año de contrato]                 INT             NULL,
    [Mes de contrato]                 NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden de mes]                    INT             NULL,
    Prueba                            INT             NULL
);

