CREATE TABLE [rrec].[registros_estudiantiles] (
    [id_registro_estudiantil]       INT           NOT NULL,
    [Clave_estudiante]              INT           NOT NULL,
    [Clave_periodo]                 VARCHAR (6)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Clave del status del alumno]   NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_estado_estudiante]       INT           NULL,
    [Status del alumno]             NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del tipo de alumno]      NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_tipo_estudiante]         INT           NULL,
    [Tipo de alumno]                NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave de la residencia]        NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_tipo_residencia]         INT           NULL,
    [Residencia]                    NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Rate]                          VARCHAR (64)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_programa]                BIGINT        NULL,
    [Clave del programa]            NVARCHAR (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa]         INT           NULL,
    [Programa]                      NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_programa_alterno]        INT           NULL,
    [Clave del programa alterno]    NVARCHAR (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa_alterno] INT           NULL,
    [Programa alterno]              NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Código de la escuela]          NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_escuela]                 INT           NULL,
    [Escuela]                       NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave de la carrera]           NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_carrera]                 INT           NULL,
    [Carrera]                       NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del Nivel Educativo]     NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Nivel]                         NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nivel_educativo]         INT           NULL,
    [Nivel Educativo]               NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del Grado Académico]     NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_grado_academico]         INT           NULL,
    [Grado Académico]               NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del tipo de admisión]    NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_tipo_admisión]           INT           NULL,
    [Tipo de admisión]              NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [no_clave_periodo_admision]     INT           NULL,
    [Clave_periodo_admision]        VARCHAR (6)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Clave del campus]              NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_universidad]             INT           NULL,
    [Campus]                        NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [no_orden_facultad]             INT           NULL,
    [nb_facultad]                   NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Status del alumno (Calculado)] NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

