CREATE TABLE [rrec].[solicitudes] (
    [id_solicitud]                  INT           NOT NULL,
    [Clave_estudiante]              INT           NOT NULL,
    [Periodo (SOL)]                 VARCHAR (6)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Descripción periodo (SOL)]     NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Aplicacion_solicitud]          INT           NOT NULL,
    [id_fecha_solicitud]            INT           NOT NULL,
    [fecha_solicitud]               DATETIME      NULL,
    [Fecha_desicion]                DATETIME      NULL,
    [Preferencia solicitud]         INT           NOT NULL,
    [Flag registro estudiantil]     VARCHAR (3)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Clave_sitio]                   VARCHAR (3)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Clave del Status de solicitud] VARCHAR (3)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Status de solicitud]           NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_estado_solicitud]        INT           NULL,
    [Orden_programa]                BIGINT        NULL,
    [Clave del programa]            NVARCHAR (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa]         INT           NULL,
    [Programa]                      NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [orden_programa_alterno]        INT           NULL,
    [Clave del programa alterno]    NVARCHAR (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_nombre_programa_alterno] INT           NULL,
    [Programa alterno]              NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave del tipo de admisión]    NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_tipo_admisión]           INT           NULL,
    [Tipo de admisión]              NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Clave de la decisión]          VARCHAR (3)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orden_decisión_admisión]       INT           NULL,
    [Decisión]                      NVARCHAR (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [no_orden_facultad]             INT           NULL,
    [nb_facultad]                   NVARCHAR (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

